from pathlib import Path
import json,re
p=Path('output/assets/business-terms.json');entries=json.loads(p.read_text());known={e['term'].casefold() for e in entries};category=''
categories={'Strategy':('Strategy','small-business','Business model'),'Finance':('Finance','business-funding','Cash flow'),'Funding':('Funding','business-funding','Loan'),'Marketing':('Marketing','digital-marketing','Content marketing'),'Sales':('Sales & Customers','customer-experience','Customer journey'),'Operations':('Operations','business-workflows','Workflow'),'People':('Leadership & Work','leadership','Leadership'),'Technology':('Technology','digital-safety','Authorization'),'AI':('AI & Technology','ai-foundations','Artificial intelligence'),'Design':('Web & Design','web-design','User experience'),'Learning':('Learning & Design','learning-products','Learning objective'),'Business Lingo':('Business Lingo','purpose-momentum','Mission'),'Projects':('Project Delivery','project-management','Acceptance criteria'),'Commerce':('Digital Commerce','small-business','Business model'),'Data':('Research & Data','digital-marketing','Metric'),'Other':('Business Essentials','small-business','Business plan')}
notes={'Authentication':'Authenticate means establish that an identity claim is genuine. Compare authorization, which concerns permission.','Authorization':'Authorize means give permission. Identity checking and permission checking are separate jobs.','B2B':'Initialism for business to business. The numeral 2 is read as “to.”','B2C':'Initialism for business to consumer. The numeral 2 is read as “to.”','CSS':'Initialism for Cascading Style Sheets. Cascading describes how applicable style rules are resolved.','HTML':'Initialism for HyperText Markup Language. Markup describes structural labels in the document.','SVG':'Initialism for Scalable Vector Graphics. Vector shapes can scale without the same pixel structure as a photograph.','XML':'Initialism for Extensible Markup Language. Tags mark the structure of information.','KDP':'Initialism for Kindle Direct Publishing. This is a named platform, so its requirements should be checked at the publisher.','ADDIE':'An acronym formed from Analyze, Design, Develop, Implement, and Evaluate. The stages can be revisited as evidence changes.','EBITDA':'An acronym for Earnings Before Interest, Taxes, Depreciation, and Amortization. It is a defined earnings measure, not the same as available cash.','Year over year':'A time-comparison phrase. Compare equivalent periods and state which year and measure you mean.','Year to date':'A time-range phrase. State the year, ending date, and measure so readers can interpret the result.','Markup':'Mark plus up describes an addition to cost. Markup on cost and margin on sales use different denominators.','Capital expenditure':'Capital identifies a longer-lived resource; expenditure means spending. The accounting treatment depends on the asset and applicable rules.','Retrieval-augmented generation':'Retrieval obtains relevant material, augmented means supplemented, and generation produces a response. Retrieved evidence still needs checking.','Multifactor authentication':'Multi means more than one; factor identifies a distinct kind of authentication evidence. Two passwords are not necessarily two different factors.','Print on demand':'On demand describes production after a request or order rather than all stock being produced beforehand.','Zero-based budgeting':'Zero-based describes rebuilding the case for spending rather than accepting the previous budget unchanged.','X-axis':'X names the horizontal coordinate in a common chart convention. Read the actual axis label and units.','Neural network':'A computational term inspired by networks of connections. It does not mean the system has a human brain or experience.'}
pairs={'Acquisition':'Merger','Agile':'Sprint','Alignment':'Learning outcome','Benchmark':'Metric','Business ethics':'Code of conduct','Capacity planning':'Bottleneck','Cost-benefit analysis':'Opportunity cost','Efficiency':'Effectiveness','Effectiveness':'Efficiency','Quality assurance':'Quality control','Quality control':'Quality assurance','Scalability':'Economies of scale','Vertical integration':'Supply chain','Accounting period':'Fiscal year','Bad debt':'Allowance for doubtful accounts','Bank reconciliation':'Bookkeeping','Contribution margin':'Fixed cost','Current asset':'Current liability','Current liability':'Current asset','Depreciation':'Amortization','Fixed cost':'Variable cost','Variable cost':'Fixed cost','Gross margin':'Markup','Markup':'Gross margin','Liquidity':'Solvency','Solvency':'Liquidity','Net income':'Net profit','Operating profit':'Operating expense','Profit and loss statement':'Income statement','Purchase order':'Invoice','Return on investment':'Return on ad spend','Secured loan':'Unsecured loan','Unsecured loan':'Secured loan','Angel investor':'Venture capital','Brand identity':'Brand voice','Brand voice':'Brand identity','Customer retention':'Churn','Churn':'Customer retention','Landing page':'Call to action','Split testing':'A/B test','B2B':'B2C','B2C':'B2B','Cross-selling':'Upselling','Upselling':'Cross-selling','Pipeline':'Sales funnel','Authentication':'Authorization','Authorization':'Authentication','AI agent':'Automation','Fine-tuning':'Prompt','Supervised learning':'Unsupervised learning','Unsupervised learning':'Supervised learning','User experience':'User interface','User interface':'User experience','Formative assessment':'Summative assessment','Summative assessment':'Formative assessment','Qualitative research':'Quantitative research','Quantitative research':'Qualitative research','Lead time':'Cycle time','Cycle time':'Lead time','Zero trust':'Least privilege','Year over year':'Year to date','Year to date':'Year over year','Leadership':'Delegation'}
pronunciations={'B2B':'bee too bee','B2C':'bee too see','CSS':'see ess ess','HTML':'aych tee em el','SVG':'ess vee jee','XML':'ex em el','KDP':'kay dee pee','ADDIE':'AD-ee','EBITDA':'ee-BIT-dah','Jira':'JEE-ruh','X-axis':'ex AK-sis','PESTLE analysis':'PES-ul uh-NAL-uh-sis','SWOT analysis':'swot uh-NAL-uh-sis','API':'ay pee eye'}
for line in Path('output/editorial/dictionary-expansion.tsv').read_text().splitlines():
 if line.startswith('# '):category=line[2:];continue
 if not line.strip():continue
 term,definition,example=line.split('|');
 if term.casefold() in known:continue
 cat,course,related=categories[category];parts=re.findall(r"[A-Za-z]+",term)
 note=notes.get(term,('Compound '+cat.lower()+' phrase. Read the words together to identify one idea; use the definition and example rather than assuming each everyday word keeps its usual meaning.' if len(parts)>1 else 'A '+cat.lower()+' term. The example shows its use as a noun or label in this context; the same word can have other meanings outside this setting.'))
 aliases=[]
 for abbreviation,full in [('SLA','Service-level agreement'),('ROI','Return on investment'),('ROAS','Return on ad spend'),('CAC','Customer acquisition cost'),('NLP','Natural language processing'),('RAG','Retrieval-augmented generation'),('MFA','Multifactor authentication'),('SaaS','Software as a service'),('POD','Print on demand'),('IP','Intellectual property'),('PO','Purchase order'),('AOV','Average order value'),('P&L','Profit and loss statement')]:
  if term==full:aliases.append(abbreviation)
 entries.append(dict(term=term,category=cat,pronunciation=pronunciations.get(term,''),partOfSpeech='noun phrase' if len(parts)>1 else 'noun',definition=definition,example=example,aliases=aliases,wordNotes=note,related=pairs.get(term,related),course=course,id=re.sub(r'[^a-z0-9]+','-',term.lower()).strip('-')));known.add(term.casefold())
entries.sort(key=lambda e:e['term'].casefold());ids=[e['id'] for e in entries];assert len(ids)==len(set(ids));terms={e['term'] for e in entries};assert all(e['related'] in terms for e in entries),[e['related'] for e in entries if e['related'] not in terms]
p.write_text(json.dumps(entries,ensure_ascii=False,indent=2));print('Published original dictionary entries:',len(entries));print({ch:sum(e['term'][0].upper()==ch for e in entries) for ch in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'})
