from pathlib import Path
import re,html
from shared_footer import footer_markup
home=Path('output/index.html').read_text();E=html.escape
header=re.search(r'<header>.*?</header>',home,re.S)[0]
for anchor in ['top','our-world','courses','articles','resources','contact']:
 header=header.replace('href="#'+anchor+'"','href="index.html'+('' if anchor=='top' else '#'+anchor)+'"')
header=header.replace('data-logo="ie"','src="assets/ie-logo.svg"')
release=re.search(r'<aside class="release-panel".*?</aside>',home,re.S)[0];release=re.sub(r'src="data:image/jpeg;base64,[^"]+"','src="assets/release-cover.svg"',release)
services=[
('01','Business & Organizations','Practical systems that support the way your business works. We connect strategy, AI, digital experiences, and content around a clearly defined goal.',['AI strategy and human-reviewed workflow planning','Business websites, interactive tools, and digital systems','Brand messaging, content development, and creative media','Marketing planning and customer communication'],'AI & business workflow','Discuss business solutions'),
('02','Education & Training','Learning experiences designed around what people need to understand and do. We combine instructional design with practical technology and purposeful interaction.',['Instructional design, curriculum, and learning paths','Interactive e-learning, scenarios, and knowledge checks','Training resources, educational media, and job aids','Professional learning and AI-supported teaching workflows'],'Instructional design & learning','Discuss a learning project'),
('03','Intentional Living','Practical AI-assisted planning for everyday priorities. We help turn scattered ideas and recurring tasks into manageable systems that fit real life.',['Organization, productivity, and personal planning','Household routines and practical digital resources','AI-assisted planning with clear human decisions','Simple tools that support goals and steady progress'],'Partnership or general inquiry','Discuss practical planning')]
from urllib.parse import quote
cards=''.join('<section class="service-card"><span class="service-symbol">'+n+'</span><h2>'+E(title)+'</h2><p>'+E(desc)+'</p><ul>'+''.join('<li>'+E(x)+'</li>' for x in bullets)+'</ul><a class="platinum" href="index.html?service='+quote(service,safe='')+'#contact">'+E(cta)+' →</a></section>' for n,title,desc,bullets,service,cta in services)
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Services | InAct Entertainment</title><meta name="description" content="AI-powered solutions for business, education, and intentional living. Explore InAct Entertainment’s digital systems, instructional design, and creative services."><link rel="canonical" href="https://inactentertainment.github.io/ie/services.html"><link rel="stylesheet" href="assets/site.css"><link rel="stylesheet" href="assets/article.css"><link rel="stylesheet" href="assets/courses.css"><link rel="stylesheet" href="assets/learning-ui.css"><link rel="stylesheet" href="assets/business-dictionary.css"><link rel="stylesheet" href="assets/brand-refresh.css"></head><body class="article-page services-page" id="top"><a class="skip" href="#services-main">Skip to services</a>'''+header+release+'''<main class="article-shell" id="services-main"><div class="article-hero"><span class="eyebrow">Create with InAct</span><h1>Ideas with purpose.<br>Systems that work.</h1><p class="deck">AI-powered solutions for business, education, and intentional living.</p><p>We bring together AI, digital media, instructional design, and practical strategy to help people and organizations work smarter, learn better, and create useful experiences.</p></div><div class="service-grid">'''+cards+'''</div><section class="service-discovery"><span class="eyebrow">Start with a conversation</span><h2>Something different in mind?</h2><p>Tell us what you want to accomplish, who it is for, and what is getting in the way. A project discovery conversation helps us identify a useful next step, define the scope, and decide whether InAct is the right fit.</p><div class="service-process"><div><strong>01 · Understand</strong><p>Identify the audience, need, and desired result.</p></div><div><strong>02 · Shape</strong><p>Agree on priorities, deliverables, constraints, and review points.</p></div><div><strong>03 · Build & refine</strong><p>Develop a focused experience, test it, and improve it using feedback.</p></div></div><p>Project scope, timing, and pricing are discussed after we understand the work. This page starts an inquiry; it does not process a purchase.</p><div class="reader-actions"><a class="platinum" href="index.html?service=Partnership%20or%20general%20inquiry#contact">Discuss a custom project →</a><a class="outline" href="index.html#our-world">Explore our portfolio →</a></div></section></main>'''+footer_markup(home).replace('../','')+'''<div class="toast" id="toast" hidden role="status"></div><script src="assets/site.js"></script><script src="assets/footer.js"></script></body></html>'''
Path('output/services.html').write_text(page);print('Built Services page')
