"""Original introductory teaching units. Full curriculum modules remain planned."""
import html,json
E=html.escape
# Three teaching sections, one worked example, one transfer task, and three decisions per course.
units={
'purpose-momentum':[
('Give purpose a practical job','Purpose is a reason that helps you choose what deserves your time. It is not a promise that every day will feel inspiring. Start with a person, a problem, and a useful change. “I want to learn AI” names a subject. “I want to organize customer questions so I can reply clearly” names a result. You can act on the second statement and see whether your work helped. Your reason can change as you learn more.'),
('Make the start small enough','A routine connects an action to a moment you can recognize. Choose a cue, a small action, and a record. For example, after opening your work calendar, spend ten minutes reviewing one lesson and write one sentence about what you can use. Reduce the effort required to begin: leave the lesson bookmarked and prepare your notebook. A missed day is information about the plan. It is not evidence that you are incapable of learning.'),
('Review without judging yourself','Momentum comes from repeating a useful action and adjusting it. At the end of a week, compare your planned practice with what actually happened. Ask what made starting easy, what interrupted you, and what result you produced. Measure work you can show rather than enthusiasm alone. If ten minutes worked, repeat it before making the plan larger. If the routine failed, change the cue or task and test again.'),
'A learner wants to create an online shop but plans three hours of study every evening. Family responsibilities make that impossible. They change the plan to twelve minutes after lunch on four days. On the first day they describe one customer. Next they write one offer, list its costs, and ask a potential customer one question. At the weekly review they have a small business test instead of a long list of unfinished videos. The useful change is a repeatable routine tied to a result, not simply more study time.',
'Write a purpose sentence naming the person, problem, and useful change. Choose one cue and a ten-minute action for the next seven days. Keep a short record of what you did. After a week, revise one part of the plan using your record.',
[('Which goal is easiest to test?',['Become successful','Help three customers understand an offer','Feel inspired every day'],1,'A named audience and observable result make a goal easier to test.'),('You miss two evenings of study. What helps first?',['Increase the daily workload','Review the cue and available time','Discard the goal'],1,'Adjust the plan using what happened rather than adding pressure.'),('What is the strongest review evidence?',['A completed small task and a practice record','The number of tabs open','A motivational quote'],0,'Your artifact and record show what you actually tried.')]],
'leadership':[
('Leadership is a shared result','Leadership involves helping people move toward a useful result. A title can give authority, but influence also comes from clarity, care, reliability, and listening. A family member planning a move, a volunteer coordinating a project, and a manager guiding a team all face leadership decisions. Begin by making the purpose clear. Ask who is affected, what success means, and who needs a voice. Responsibility includes checking that people understand the plan, not only giving instructions.'),
('Choose a style for the situation','Leadership styles describe patterns of behavior, not permanent personality boxes. A directive approach gives clear instructions when time is short or a task is unfamiliar. A participative approach invites ideas when the group has useful experience. Coaching helps a person develop a skill through questions, practice, and feedback. Delegation gives a capable person room to act within agreed boundaries. Any style can fail when used without context. Explain the reason for your choice and review its effect.'),
('Make accountability fair','Accountability means knowing who will do what, by when, and how progress will be checked. It works best when people have the information and support needed to succeed. Name a decision owner and a place to raise concerns. Separate a behavior from a person’s worth: “The update arrived late” gives you a problem to solve; “You are unreliable” closes the conversation. AI can draft an agenda or organize feedback. A leader remains responsible for listening, judgment, and follow-through.'),
'A neighborhood group needs a weekend cleanup. The organizer first asks residents about access needs and available hours. They agree on a shared result and assign small roles. During a sudden safety issue, the organizer gives direct instructions. Afterward, the group returns to a participative discussion about improving the plan. A new volunteer receives coaching; an experienced volunteer handles supplies within a spending limit. The organizer is changing behavior to fit the situation rather than insisting on one style everywhere.',
'Choose a real group task. Write its purpose, three responsibilities, a decision boundary, and a check-in time. Select a leadership style for one moment and explain why it fits. Ask a participant what remains unclear, then revise the plan.',
[('Who can practice leadership?',['Only a person with a management title','Anyone helping a group reach a useful result','Only the oldest person'],1,'Leadership can be practiced through influence and responsibility without a formal title.'),('An experienced colleague needs room to complete a familiar task. What fits?',['Detailed control of every movement','Delegation with clear boundaries','No agreed result'],1,'Capability plus agreed authority makes delegation useful.'),('Which feedback is most actionable?',['You always let everyone down','The update was late; what blocked it?','Everything is fine'],1,'Name the behavior and investigate the cause without attacking the person.')]],
'ai-foundations':[
('Separate the app from the model','An app is the interface you use. A model is a system inside or behind it that produces a result from patterns learned during training. Generative AI can produce text, images, audio, or code. It can make useful drafts and convincing mistakes. Different tools have different inputs, limits, and data practices. Choose a tool for a task you understand before comparing many products. A confident answer does not prove that the system checked a fact.'),
('Write a request with enough context','A useful prompt states the goal, relevant context, constraints, and desired format. Instead of “write an email,” explain the audience, purpose, known facts, and tone. Ask the tool to identify missing information rather than invent it. You can request a short draft or a table, then revise the result. Avoid adding private information just to make the prompt more detailed. Use a fictional or approved example when practicing with sensitive work.'),
('Check the result against reality','Review an AI answer by checking facts, completeness, usefulness, and risk. Compare dates and figures with original records. Open cited sources and confirm that they support the claim. For code, test the behavior; for a plan, test whether it fits the real constraints. Some tasks need a knowledgeable person’s review before the result is used. The important skill is knowing what you can verify and where you need help.'),
'A shop needs an email announcing a changed opening time. The owner supplies the verified date, new hours, audience, and a request for three short sentences. The first draft adds a discount that does not exist. The owner removes the discount and asks the tool to use only supplied facts. They compare the final version with the calendar before sending. The tool helped write the message; the owner supplied the authority and the factual check.',
'Use fictional details to draft a meeting agenda. Include a goal, audience, known facts, length, and format. Mark each statement as supplied fact, reasonable suggestion, or unsupported addition. Revise the draft and record one limitation.',
[('What is a model?',['The name of every AI website','A system that produces results from learned patterns','A guarantee of accuracy'],1,'An app is an interface; the model is part of the system producing the output.'),('What should a prompt do when a date is missing?',['Ask the tool to invent a likely date','Identify the missing detail','Hide the uncertainty'],1,'Missing information should remain visible until verified.'),('A citation looks official. What next?',['Accept the answer','Open the source and check the claim','Remove all citations'],1,'A source must exist and support the specific claim.')]],
'music-ai':[
('A song and a recording are different','A song is a musical composition, including its words when it has lyrics. A recording is a captured performance or produced version of that song. One song can have many recordings. Songwriters, performers, producers, publishers, labels, and distributors have different jobs, though one person may do several. Learn those roles before trying to understand a royalty statement. A streaming release connects creative work, rights, delivery, listener discovery, and payment; a generator handles only part of that chain.'),
('Technology changes how music travels','Printed music helped songs circulate; recordings let people hear a performance again; radio brought programs into homes; downloads and streaming changed access. This is a broad map, not a complete history. Each change altered the tools and the business around listening. AI adds ways to draft lyrics, explore sounds, or develop musical material. It does not tell you why a track matters. Human direction still includes choosing a listening experience, making edits, and explaining the experiment honestly.'),
('Begin with a creative brief and a rights check','A creative brief names the mood, audience, listening setting, structure, and choices you want to explore. Compare drafts against that brief instead of generating endlessly. Keep a record of the tools, inputs, edits, permissions, and people involved. Copyright questions about AI depend on the actual human contribution and circumstances; a tool’s commercial-use terms do not settle every legal issue. Check the current distributor requirements and the material you plan to release. Do not assume permission to imitate someone’s identity or voice.'),
'A creator wants an original track for an evening walk. They write a brief: steady pace, warm texture, an uncluttered arrangement, and space for a reflective vocal. They compare three drafts using those listening goals. One has a strong opening but too many layers, so they revise it instead of discarding the whole idea. They document their choices and check the inputs, tool terms, credits, and release requirements. This creates an explainable project rather than an anonymous pile of generated tracks.',
'Map the roles involved in one release. Write a short listening brief and compare two examples using audible details. Make a separate checklist for rights, identity, credits, delivery, and promotion. Use the deeper InAct music lessons after these basic roles make sense.',
[('What can have several recordings?',['One musical composition','Only a distributor account','A payment receipt'],0,'A song can be recorded and performed in different versions.'),('What makes a draft useful to your project?',['It is the newest generation','It fits a stated listening goal','It has the most layers'],1,'A creative brief gives you reasons for selecting and revising material.'),('Commercial-use tool terms settle every rights question.',['True','False'],1,'Tool terms and copyright or identity questions are separate checks.')]],
'everyday-ai':[
('Choose one repeated source of friction','Everyday AI works best when it helps with a task you can describe. Choose something repeated: planning appointments, sorting a shopping list, preparing a message, or organizing study notes. Write how you handle it now and what goes wrong. Do not begin by moving every part of life into one app. A small trial reveals whether the technology reduces effort or adds another thing to manage. Keep the original information available while you test.'),
('Give the plan real constraints','A useful plan accounts for time, energy, travel, care responsibilities, and other commitments. AI can suggest a schedule, but it cannot know constraints you did not provide or verify. Use approved or fictional information when you practice. Keep sensitive health, identity, and financial records out of an unfamiliar tool. For important personal decisions, use the original source and qualified support as needed. AI can help prepare questions without pretending to have the final answer.'),
('Keep ownership of the routine','A life flow is a repeatable path from a need to a useful result. A weekly planning flow might collect commitments, check a calendar, choose priorities, and review what changed. Decide who checks the draft and where the final plan lives. Keep a simple fallback for days when a tool is unavailable. Judge the system by fewer missed commitments or clearer decisions, not the number of automations. Revise the routine when your life changes.'),
'A parent asks for a weekly activity plan using a fictional family schedule. The draft puts a grocery trip between two appointments without travel time. They correct the constraints and reduce the number of activities. The final plan lives in the calendar the household already uses. A paper checklist remains available. The helpful result is a realistic week that people understand, not a complicated new dashboard.',
'Choose one repeated life task. Map its current steps, name the source of each fact, and draft a simpler routine. Test it for one week. Record what you still had to check and whether the routine actually saved effort.',
[('Which task is a useful first trial?',['Automate every life decision','Draft a weekly plan you can check','Upload every private record'],1,'Begin with a bounded task and a result you can verify.'),('What belongs in a realistic schedule?',['Only the appointment time','Travel and other commitments as well','Every suggested activity'],1,'Real constraints determine whether a plan is usable.'),('What shows that a routine helped?',['More apps installed','Fewer missed commitments','More automatic notifications'],1,'Measure the useful change rather than tool activity.')]],
'organization':[
('Build one trusted capture point','Organization begins with knowing where a new commitment goes. A capture point can be a notebook, task app, or simple list. It should be easy to reach and checked regularly. Capture does not mean keeping every detail forever. When you review an item, decide whether it is an action, reference material, a scheduled event, or something to discard. “School paperwork” is vague; “sign the field-trip form by Thursday” names an action and a deadline.'),
('Give information a home','Separate tasks from files. A task tells you what to do; a file holds information you may need. Choose simple folders that reflect your real work, then use names that help you find things later. A date, project, and short description can be more useful than “final-final.” For household documents, decide who can access them and how they are protected. For family routines, make responsibilities clear without treating people as items to control. AI can suggest categories; review them before moving or deleting files.'),
('Make maintenance part of the system','A system stays useful when you review it. Each week, check open tasks, the next calendar dates, loose notes, and missing documents. Archive finished work and keep backups for important files. Test whether you can restore a file, not merely whether a backup icon appears. Avoid building a perfect filing system before solving the biggest daily problem. Your first goal is finding what matters and knowing the next action. Add complexity only when a real need appears.'),
'A household has forms in email, bills on a counter, and reminders in three apps. They create one capture list and review it each evening. A school form becomes an action with a due date; a paid bill becomes a protected reference file; an appointment goes on the shared calendar. They agree on who handles each action. Once a week they check for unfinished items and back up important documents. The system makes responsibility visible without requiring everyone to learn five new tools.',
'Collect ten loose items from your home or work. Classify each as action, reference, calendar, or discard. Give the actions clear verbs and deadlines where needed. Create a small folder map and a weekly review checklist. Try finding three files without using memory alone.',
[('Which item is an action?',['Sign the form by Thursday','A copy of last year’s receipt','A brochure you no longer need'],0,'An action names work you can do.'),('What should happen before AI reorganizes files?',['Let it delete anything similar','Review the proposed changes and backup','Remove file names'],1,'Review and recovery protect you from mistaken changes.'),('Why have a weekly review?',['To redesign every folder','To keep tasks and information trustworthy','To collect more apps'],1,'Regular maintenance prevents the system from becoming another pile.')]],
'small-business':[
('Choose a customer and a problem','A small business begins with a useful offer to a particular customer. Ask what the person is trying to accomplish, what they use now, and what is difficult about it. A customer interview is a chance to learn, not force agreement. Ask for examples of recent behavior instead of asking whether someone likes your idea. AI can help draft neutral questions and summarize approved notes. Real people and real choices provide evidence that a generated market description cannot supply.'),
('Understand the money in one sale','Revenue is the money a sale brings in. Costs include materials, fees, fulfillment, time, and other expenses. Profit and cash flow answer different questions: whether the business earns more than it spends and when money arrives or leaves. A business can look profitable while lacking cash for a bill due today. Start with a simple cost sheet for one offer. Use actual quotes where possible and mark estimates. Keep personal and business records organized, and check official requirements for your location.'),
('Test before building a large system','A small test has an audience, an offer, a limited budget, a way to deliver, and a result to review. A landing page or sample can help explain the offer, but a nice logo is not demand. Decide what would make you continue, revise, or stop. Related courses explore print on demand, Amazon, digital products, funding, customer experience, and scaling. Choose the route that fits your evidence rather than treating all of them as required steps.'),
'A founder wants to sell custom welcome guides to small rental hosts. They interview five hosts about recent guest questions and draft one sample using fictional property details. The cost sheet includes design time, revision time, and payment fees. They offer a small paid pilot with a clear scope. After delivery they review what customers used and how long the work took. That evidence guides pricing and product changes before they buy a large software stack.',
'Write a one-page offer with a named customer, problem, result, scope, and estimated costs. Design a small test and a review rule. Identify which registration, tax, permission, or insurance questions need official answers before trading.',
[('What is stronger customer evidence?',['An AI prediction alone','A recent example of a customer’s problem','A compliment on your logo'],1,'Actual behavior is more useful than a speculative description.'),('Profit and cash flow are the same.',['True','False'],1,'Profit and the timing of available cash are different.'),('What should a first test include?',['An unlimited budget','A result that guides the next decision','Every possible product'],1,'A test needs a decision rule and bounded effort.')]],
'scale-business':[
('Growth and scale ask different questions','Growth increases activity or revenue. Scaling aims to increase useful output without costs and coordination rising at the same rate. The words are sometimes used loosely; the practical distinction is capacity. If doubling orders requires doubling every hour of work, your current system has grown but has not gained much leverage. Before expanding, understand demand, delivery quality, cash needs, and the work that limits output. Bigger is not automatically healthier.'),
('Find the bottleneck before buying automation','A bottleneck is the step that limits the whole flow. If production is fast but every order waits for approval, speeding up production makes a larger queue. Map the work and measure where it waits. You might improve a template, train another reviewer, change the offer, or remove unnecessary steps. AI can assist repeatable preparation, but a rushed automated decision can create expensive mistakes. Separate tool access from authority, and test unusual cases before increasing volume.'),
('Scale a process you can explain','A repeatable process has clear inputs, quality checks, responsibilities, and exceptions. Document the minimum needed for another person to deliver the result well. Track margin, repeat demand, rework, and available cash alongside revenue. Expansion may require hiring, financing, or a different service model; those choices have obligations. Use verified figures and suitable professional advice for major decisions. Run a limited pilot before committing to a much larger operation.'),
'A design service receives twice as many requests, but the owner must approve every draft. They first measure review time and identify common corrections. A checklist lets a trained teammate resolve routine issues while unusual claims still go to the owner. They pilot the process with ten projects and compare rework, delivery time, and cost. They do not buy more leads until delivery capacity is reliable. The improvement addresses the constraint that was actually slowing the business.',
'Map one business process and estimate its capacity. Identify the limiting step using evidence. Propose one bounded change, a quality check, and a pilot measure. Explain what must remain under human authority.',
[('What is a sign of useful scale?',['Output rises while unit effort falls and quality holds','Revenue rises while every cost doubles','More dashboards alone'],0,'Leverage and reliable quality matter alongside growth.'),('Orders wait for approval. What should you examine?',['Only advertising','The review bottleneck','The logo color'],1,'Improve the limiting step before adding more work.'),('What comes before broad rollout?',['A limited pilot with measures','Removing all review','Hiring without a process'],0,'A pilot reveals quality and exception problems.')]],
'print-on-demand':[
('Understand who does each job','Print on demand usually means a product is produced after a customer places an order. A fulfillment provider may print and ship it; the seller still needs to understand design rights, the offer, customer promises, fees, and support. Different platforms divide those jobs differently. The model can reduce inventory held in advance, but it does not remove costs or business responsibility. Start by mapping the customer, storefront, production partner, payment, and support path.'),
('Calculate a margin before adding products','A sale price is not your earnings. Subtract the relevant production, shipping, platform, payment, promotion, and expected support or return costs. Some costs are estimates, so test realistic scenarios. Order a sample when feasible to inspect print quality, fit, packaging, and delivery. Do not copy a popular character, brand, or artwork because it appears in search results. AI-generated artwork still needs a rights and quality review. Read the actual provider terms before promising delivery or returns.'),
('Build a small, coherent test','Choose a specific audience and a small collection with a clear theme. Explain the product using accurate images and descriptions. Check how the listing appears on a phone and what the customer sees at checkout. AI can help draft copy or compare design variations, but you review every claim. Keep a record of costs and customer questions. A useful first experiment tests demand, quality, and delivery together; listing hundreds of untested designs can hide the problems.'),
'A creator tests three gardening-themed shirts using original designs. In an illustrative estimate, a $28 sale has $14 production, $5 shipping, and $3 combined fees, leaving $6 before promotion, taxes, and other expenses. A $7 ad cost would erase that contribution. They order a sample and adjust an unreadable design before promoting it. These numbers are a teaching example, not a provider quote or earnings forecast.',
'Map one proposed product from order to delivery. Create a cost sheet using current provider quotes. Check the design’s rights, order a sample if practical, and write a limited test plan with a budget and a customer-support route.',
[('What does print on demand reduce?',['Every business cost','The need to hold some inventory in advance','The need for support'],1,'Production after ordering does not remove fees or responsibility.'),('A $28 sale with $22 relevant costs leaves what before other expenses?',['$28','$6','$22'],1,'Subtract the costs included in the example; other costs may still apply.'),('What is the best first collection?',['Hundreds of unreviewed designs','A small original collection with quality checks','Copied popular logos'],1,'A small coherent test makes quality and demand easier to evaluate.')]],
'amazon-business':[
('Choose a route before opening accounts','Amazon contains several distinct business routes. KDP is for publishing books; ACX connects eligible audiobook projects and production; Merch on Demand concerns approved merchandise; selling programs involve products and fulfillment; Associates involves qualifying referrals. Business purchasing and B2B selling add other uses. These routes have different eligibility, costs, rights, and responsibilities. This course maps major routes rather than promising every possible opportunity. A person should choose based on a useful offer and the work they can deliver.'),
('Publishing is not the same as product selling','For books, you need useful original material, proper formatting, rights, and honest metadata. KDP distinguishes AI-generated material, which must be disclosed under its current guidance, from AI-assisted work. For audiobooks, check ACX’s current narration and authorization rules; ordinary unauthorized text-to-speech is not simply an acceptable shortcut. Merch requires rights-compliant designs and platform eligibility. Product selling can involve sourcing, listing accuracy, inventory, and fulfillment. FBA does not make storage and fulfillment costs disappear.'),
('Compare responsibilities and test economics','Build a comparison sheet for the route you are considering. Record eligibility, the customer, content or product rights, costs, quality standards, how payment works, and who handles support. Check official pages because terms and fees can change. AI can help organize that research, but verify each claim at the platform. Do not buy expensive inventory or assume account approval based on a tutorial. Referral content also needs clear disclosures where required. Begin with one route and a manageable test.'),
'A creator compares a short practical workbook, a shirt collection, and a sourced physical product. They already have teaching experience but no inventory operation, so they investigate KDP first. They review the current content rules, build an original sample, check formatting, and calculate printing economics. They keep ACX and Merch as separate future options with their own requirements. Choosing one route lets them learn the work rather than confusing three different systems.',
'Compare two Amazon routes in a table. Include eligibility, rights, production tasks, fees, support, and a verification link. Choose one and outline a small quality-controlled test. Mark every unanswered requirement before spending money.',
[('Why compare routes first?',['They all have identical rules','Their responsibilities and requirements differ','Approval is guaranteed'],1,'Each route is a distinct operating model.'),('KDP AI-generated and AI-assisted material are treated identically in disclosure guidance.',['True','False'],1,'Check KDP’s current distinction and disclose AI-generated material as required.'),('What should an audiobook plan check?',['Only the cover','Current ACX narration and authorization rules','Whether a free TTS app exists'],1,'Do not assume any synthetic narration is permitted.')]],
'learning-products':[
('Start with a performance need','A digital learning product should help a person do something useful. Name the learner, the situation, and the task before choosing a file format. A worksheet, course, template, or small app can each solve different needs. “Understand marketing” is broad; “write a customer-focused offer and test it” gives you observable work. Ask what the person already knows and what prevents success. More content is not automatically a better product.'),
('Align the teaching and the evidence','Choose an outcome, show an example, offer practice, and provide feedback about the same skill. If the outcome is making a decision, use a realistic decision rather than only asking for a definition. Break an unfamiliar process into manageable steps. Use a diagram where it explains a relationship, not as decoration that competes with reading. AI can draft material, but you check the facts, reading level, accessibility, and whether the task actually teaches the promised skill.'),
('Test usefulness before packaging','Ask a person from the intended audience to use a small version. Observe where they hesitate and what they can do afterward. Do not rely only on whether they like the colors. Revise unclear instructions and feedback. A sale also requires accurate scope, rights to included material, delivery instructions, and support expectations. Keep versions organized so customers receive the intended file. A learning product improves when the evidence changes the design.'),
'A creator wants to sell a budgeting worksheet for first-time event organizers. Instead of adding twenty pages of explanation, they show one completed budget, provide a blank example, and ask the learner to find a missing cost. A tester overlooks transport, so the creator adds a short check and feedback. The product becomes easier to apply because it targets a real task and uses the test to improve the instructions.',
'Create a one-page prototype for a specific learner. Include an outcome, worked example, practice task, and feedback. Ask someone to use it, then record one revision based on what they actually did.',
[('Which outcome is observable?',['Become knowledgeable','Compare two offers using stated criteria','Enjoy a nice worksheet'],1,'An observable action gives you something to assess.'),('What best tests a decision skill?',['A realistic choice with reasons','A color preference','A title alone'],0,'Practice should ask for the same skill as the outcome.'),('What is useful prototype evidence?',['A learner’s actual attempt','Only compliments','File size'],0,'Observe performance and confusion, then revise.')]],
'business-funding':[
('Name the use before the source','Funding should serve a defined business need. Equipment, inventory, operating expenses, and a temporary cash gap are different uses. Write the amount, purpose, timing, expected benefit, and how the business can handle the obligation. Use verified records and mark estimates. If the need is unclear, access to more money can make the problem harder. InAct provides education and commercial funding referral on this site; it is not the lender and cannot promise approval.'),
('Understand what you give in return','Debt usually requires repayment under agreed terms. Equity gives an investor an ownership interest. Grants have specific eligibility and permitted uses; they are not a general promise of free startup money. A credit line provides access within agreed limits and conditions. Compare total cost, payment schedule, collateral or guarantees, flexibility, and the consequences of missing obligations. A lower advertised rate does not alone establish the best option. Read actual terms and ask the provider to explain uncertainties.'),
('Prepare truthful evidence','A readiness folder may include business identity records, financial statements, tax documents, bank records, and a clear use-of-funds explanation, depending on the provider. Protect those documents and share only through verified channels. AI can help organize a checklist or draft questions using approved information. It must not invent revenue, alter evidence, or submit unreviewed claims. Confirm current eligibility and compare the effect of different payment schedules on cash available for operations.'),
'A business needs equipment to fulfill confirmed orders. The owner separates the purchase price from installation, training, and maintenance. They compare an equipment option with a general loan using actual written terms. A cash forecast includes slower customer payments. Before applying, they verify the provider and prepare accurate records. The comparison may still show that delaying the purchase is safer; choosing not to borrow can be a valid decision.',
'Create a funding-readiness worksheet with a verified amount, purpose, timing, repayment or ownership implications, and unanswered questions. Compare two real provider options using current terms. Keep sensitive records private and consult appropriate professional support for a major commitment.',
[('What should come before choosing a provider?',['A clear use and verified amount','A promise of approval','An invented revenue estimate'],0,'The purpose and amount guide the comparison.'),('What does equity involve?',['No obligations at all','An ownership interest','A guaranteed grant'],1,'Equity and borrowing create different commitments.'),('How should AI help an application?',['Invent missing figures','Organize verified information for review','Submit without permission'],1,'Preparation must remain truthful and reviewed.')]],
'business-workflows':[
('Map the work that actually happens','A workflow takes an input through steps to a result. Begin with the current process, including handoffs and delays. Name what arrives, who checks it, what information is needed, and what should be produced. A customer inquiry may need classification, a record lookup, a draft reply, review, and sending. Drawing those steps exposes missing responsibilities. Automating an unclear process usually moves the confusion faster rather than solving it.'),
('Choose rules or AI deliberately','A fixed rule works well for a clear, repeatable condition. AI may help with language, summaries, or varied input, but its outputs need suitable checks. An agent can take steps using tools within its design; capability is not permission. Define what it may read, prepare, change, or send. Give the least access needed for the task. Important decisions need a named reviewer and a visible way to handle missing information or an exception.'),
('Test the boundary as well as the happy path','A successful ordinary case does not prove a workflow is reliable. Test incomplete requests, duplicates, unusual language, unavailable tools, and conflicting records. Record the input, result, reviewer decision, and errors. Keep a fallback so someone can finish the work manually. Judge the pilot by accuracy, useful time saved, and rework. Expand access only after the process performs acceptably under the cases that matter.'),
'A team wants faster customer replies. They first build a flow that reads an approved request, checks the order record, and drafts a response. A person must approve sending. A test request contains no order number, so the flow asks for missing information instead of inventing a record. A duplicate request is flagged. The pilot saves drafting time while keeping the decision boundary clear.',
'Draw a five-step workflow. Label inputs, outputs, owner, review point, and exception path. Test one normal case and two boundary cases with fictional information. Record what a person must approve before any external action.',
[('What should be mapped first?',['The current process','Every available tool','A complicated dashboard'],0,'Understand the real work before automating it.'),('An agent can send an email. Does that establish permission?',['Yes','No'],1,'Tool capability and authorized action are separate.'),('Which test matters alongside a normal request?',['Missing or conflicting information','Only the fastest case','A different logo'],0,'Boundary cases reveal important failures.')]],
'project-management':[
('Define a result people can recognize','A project is a temporary effort to create a particular result. Begin with the person who needs it and the problem it solves. Write what is included, what is outside scope, and what evidence shows completion. “Build a website” is incomplete. “Publish a mobile-friendly page with tested contact links and approved copy” gives the team something to check. Acceptance criteria describe a satisfactory result before people invest in the work.'),
('Plan tasks and dependencies','Break the result into tasks small enough to assign and review. Name an owner, an estimate, and a dependency where one task must wait for another. A schedule without dependencies can promise an impossible sequence. AI can draft a task list, but the team checks effort, constraints, and missing work. Keep a simple risk list: what could go wrong, how likely or serious it seems, and what you will do. Estimates are planning aids, not guarantees.'),
('Review progress through evidence','A useful update says what is finished, what is blocked, and what decision is needed. A percentage can hide uncertainty unless everyone agrees what it means. Show working artifacts and test them against acceptance criteria. When scope changes, record its effect on time, cost, and quality. Close the project by checking the result, transferring responsibilities, and recording lessons for the next one. Delivery is more than marking tasks complete.'),
'A team is building a workshop signup page. They agree that completion means approved text, keyboard-accessible controls, tested mobile layout, and a working signup destination. The design cannot finish before the workshop details are approved. A late request for payment processing becomes a scope change with new work and testing. The team reviews the impact rather than quietly adding it to the old deadline.',
'Write a project brief with scope and three acceptance criteria. List five tasks with owners and dependencies. Add two risks and a review date. Show what evidence will prove the result is ready.',
[('What makes completion clear?',['Acceptance criteria','A vague percentage','The longest task list'],0,'Criteria name the evidence of a satisfactory result.'),('A task depends on approved copy. What should the plan show?',['The dependency','Only the color palette','A guaranteed finish date'],0,'Dependencies reveal where work must wait.'),('A new feature appears mid-project. What next?',['Add it silently','Review scope and its impact','Ignore every request'],1,'A scope decision should account for time, cost, and quality.')]],
'digital-marketing':[
('Begin with the customer’s question','Digital marketing helps an audience find, understand, and choose an offer. Start with what the person needs to know, not how often you can post. A new visitor may ask what the service does; a interested buyer may ask about fit, evidence, or price. Write for those decisions. Search, email, social platforms, and your website have different roles. A channel is useful when it reaches the right audience with an appropriate next step.'),
('Make claims useful and supportable','A message should explain the result, the relevant evidence, and the next action. Avoid unsupported superlatives or promises. AI can suggest angles and draft variations, but you review accuracy, voice, and the customer’s context. Reuse an idea in suitable formats rather than copying identical text everywhere. If promotion involves an affiliate or paid relationship, make the relationship clear as required. Trust depends on what a person can verify, not merely polished language.'),
('Measure the action that matters','Views, clicks, inquiries, purchases, and repeat visits describe different stages. Choose a measure linked to the purpose of your test. A high-view post may be useful for awareness but may not produce qualified inquiries. Change one important element at a time where practical and keep a record of context. Small tests have noisy results; avoid declaring a universal rule from one post. Use the evidence to improve your message and destination.'),
'A local tutor publishes a short explanation of how a first session works. The page includes a sample activity and a clear inquiry link. One post gets many views but few visits; another reaches fewer people and produces relevant questions. The tutor examines the audience and message instead of assuming the larger view count wins. The next test improves the explanation of who the service is for.',
'Choose one offer and one audience question. Draft a short useful answer with evidence and a next step. Select a channel and one meaningful measure. Review the destination on a phone before running a small test.',
[('What should guide a message?',['A customer’s actual question','Only posting frequency','Whatever is trending'],0,'Useful marketing starts with the audience’s decision.'),('An AI draft claims guaranteed results. What do you do?',['Publish the claim','Remove or substantiate it','Make it larger'],1,'Claims need evidence and an honest scope.'),('Which measure best fits an inquiry campaign?',['Qualified inquiries','Only impressions','Number of fonts'],0,'Choose a measure connected to the campaign’s purpose.')]],
'customer-experience':[
('Map the buying journey','Customer experience includes what happens before, during, and after a purchase. A person may discover an offer, compare it, ask a question, pay, receive it, and need support. At each step, ask what they need to know and what could confuse them. A polished storefront cannot repair an unclear promise. Begin with one real customer path and check whether the information matches what the business can reliably deliver.'),
('Make the promise visible','An offer should explain what is included, price and relevant costs, delivery expectations, and support or return terms that apply. Do not bury important limitations under exciting language. AI can draft explanations and organize support themes, but a person must verify policy claims. Use plain language and accessible controls. If a buyer needs an answer, make the next step easy to find. Repeated questions often reveal missing information in the offer itself.'),
('Close the loop after delivery','A good support process acknowledges the issue, checks the record, explains the options, and follows through. Give staff or tools clear limits on refunds, promises, and data access. Track recurring problems and fix their causes. A short feedback request can help, but silence does not prove satisfaction. Look at repeat requests, delivery problems, and the usefulness of the result. Improve the experience without pressuring customers or inventing social proof.'),
'A template shop receives repeated questions about editing software. The owner adds compatibility details and a sample before checkout. Support replies use the actual purchase record and ask for the missing detail rather than guessing. They track the questions for a month and find fewer compatibility complaints. The improvement came from clarifying the promise, not adding more promotional popups.',
'Map an offer from discovery to support. At each stage, list one customer question and one possible failure. Improve the weakest stage, then create a support response that asks for evidence and explains the permitted next step.',
[('When does customer experience begin?',['Only after payment','Before purchase, at discovery and comparison','Only when there is a complaint'],1,'The whole journey shapes understanding and trust.'),('What helps a buyer judge fit?',['Visible compatibility and scope details','Hidden limitations','Invented reviews'],0,'Clear information prevents mismatched expectations.'),('Repeated support questions may indicate what?',['Missing information in the offer','A need to stop answering','Proof that every customer is wrong'],0,'Recurring questions can reveal a design problem.')]],
'web-design':[
('Give each layer a job','HTML describes structure and meaning, CSS controls appearance, and JavaScript adds behavior. A domain is an address; hosting makes the site available. These roles help you understand what an AI coding tool produces. Start with a page that helps a visitor complete one task. Use meaningful headings, actual links for destinations, and buttons for actions. A beautiful control is not useful if nobody can tell what it does.'),
('Design for different people and screens','Test the page on a phone and with a keyboard. Make focus visible, label inputs, provide useful alternative text, and keep text readable. Do not depend only on color or hover to explain an action. Motion should respect reduced-motion preferences and should not block reading. A simple layout can still feel engaging through spacing, contrast, and thoughtful feedback. The goal is a usable experience, not the largest number of effects.'),
('Verify behavior before calling it finished','Check links, input validation, loading and error states, and how data is handled. A static form can prepare an email without sending it; explain that honestly. A saved note may remain only in a browser. AI-generated code can contain mistakes, so test the actual result instead of trusting a description. Keep a backup of your source and a repeatable publishing method. Review the live page after deployment, not only the local preview.'),
'A creator builds a business card page with a contact form. The first version has an attractive submit button but no delivery service. They change the label to “Prepare my email” and explain that the visitor must send it from their mail app. They test keyboard focus, mobile width, and the fallback download. Honest behavior makes the small site more useful than an impressive-looking form that silently fails.',
'Build a one-page prototype with a heading, useful navigation, one action, and a labeled input. Test keyboard use, phone layout, and an error case. Write a brief note explaining exactly what is stored or sent.',
[('Which layer gives a page structure?',['HTML','A domain name','A color palette'],0,'HTML describes the structure and meaning of content.'),('Can hover be the only way to discover an important action?',['Yes','No'],1,'Touch and keyboard users also need access.'),('What verifies a form?',['Its appearance','Testing delivery and explaining the actual behavior','A button label alone'],1,'A form must do what users are told it does.')]],
'ai-content-studio':[
('Write a brief before generating','A content brief names the audience, purpose, message, format, evidence, and constraints. It gives an AI draft a job. One campaign might need a short video script, a page, and a newsletter, but each format serves a different moment. Begin with an original idea or verified source material. Do not treat unlimited generation as a content strategy. Your strongest advantage may be the clarity of your judgment and the experience behind the message.'),
('Use a human-directed production loop','A practical loop moves from brief to draft, review, revision, and publication. Separate factual checking from style editing. Keep a source record for important claims and check permissions for included media. AI can help outline, draft, summarize, or propose alternatives. It cannot establish that a claim is true simply by repeating it. When content includes synthetic identities or important edits, consider what the audience needs to understand the material honestly.'),
('Build reusable systems without losing context','Templates save time when they preserve useful decisions, not when they force every idea into the same shape. Create a small style guide, approved facts, file naming rules, and a publication checklist. Keep versions so the right file gets published. Adapt the work to the channel and audience. Review results using meaningful actions, then revise one part of the process. A studio is an organized way to make useful work, not a pile of generated files.'),
'A small business records a customer-approved demonstration. The team writes a brief and uses AI to propose a script outline. They verify the product claims, edit the pacing, and produce a short clip and a supporting page. A reviewer catches a sentence that overstates the result. They correct both versions and preserve the approved source. One production loop serves several formats while maintaining the same evidence.',
'Write a content brief, produce one small draft, and review it for facts, fit, rights, and accessibility. Create a publication checklist and a naming rule. Explain which decisions you made yourself and what the tool contributed.',
[('What comes before generating many drafts?',['A content brief','Publishing immediately','Removing source notes'],0,'A brief gives the output a purpose and boundaries.'),('Which review should be separate from style editing?',['Fact checking','Choosing a filename only','Counting adjectives'],0,'An elegant sentence can still be false.'),('What makes a template useful?',['It preserves useful decisions while allowing context','It makes all messages identical','It replaces every review'],0,'Reusable structure should support judgment.')]],
'career-ai':[
('Map evidence of your skills','A career plan begins with what you can do and the evidence that shows it. A skill may come from paid work, study, volunteering, or a personal project. Describe the task, your contribution, and a result you can support. Transferable skills include organizing work, communicating, solving problems, and learning tools. AI can help find clearer wording, but it must not invent experience or qualifications. Your goal is a truthful account that another person can understand.'),
('Choose opportunities by their tasks','Read a role as a set of tasks and requirements rather than only a title. Compare those tasks with your evidence and identify gaps. A learning project can close a small gap more convincingly than a vague claim that you are passionate. Use current employer information and verify application channels. Avoid sharing sensitive records with an unverified recruiter. AI can help organize a comparison or practice questions, but you need to check what the employer actually asks for.'),
('Practice explaining your work','An interview example can describe the situation, task, action, and result. Keep your own contribution clear and avoid claiming the team’s entire result as yours. Practice a concise explanation, then invite follow-up questions. A portfolio should show the problem, choices, artifact, and evidence of testing. If a project is a prototype, label it honestly. Review what you learn from an application and choose a next skill to practice rather than treating one response as a judgment of your worth.'),
'A learner built an interactive lesson for a volunteer group. They document the original need, their design choices, a screenshot, and what changed after a tester used it. AI helps shorten their explanation, but they remove an invented claim about learner performance. The portfolio accurately shows a tested prototype and the decisions behind it. It gives an employer evidence to discuss rather than an inflated title.',
'List three skills with one real example each. Choose a role and compare its tasks with your evidence. Build one small artifact for a gap and practice explaining the choices. Keep every claim verifiable.',
[('What makes a skill claim credible?',['A specific example and evidence','An invented job title','A longer list of buzzwords'],0,'Evidence helps another person assess the claim.'),('How should you compare roles?',['By tasks and requirements','Only by the title','Only by a viral salary post'],0,'The actual work determines fit and learning needs.'),('A portfolio prototype should be described as what?',['A completed commercial deployment','A prototype with accurate testing details','An accredited credential'],1,'Honest scope makes the evidence meaningful.')]],
'digital-safety':[
('Protect accounts before adding more tools','An account can connect messages, money, documents, and identity. Use unique passwords, a reputable password manager, and multifactor authentication where available. Keep devices and apps updated, and know how account recovery works. These practices reduce risk; none is a promise of perfect safety. Begin with the accounts whose loss would cause the most trouble. A short recovery plan is more useful than assuming you will remember every detail during a problem.'),
('Slow down suspicious requests','A message can imitate a familiar person or brand. Urgency, unusual payment instructions, unexpected attachments, and requests for codes deserve a pause. Verify through a channel you already trust instead of using the link or number in the suspicious message. AI-generated text, images, or voices can make impersonation more convincing, but familiar appearance has never been enough evidence. Do not share login codes or private records to satisfy an unverified request.'),
('Keep data and authority bounded','Before using an AI app, consider what information it receives, how it may be stored, and whether your organization allows it. Use fictional data to practice. Keep backups of important files and test restoration. If a tool can take actions, give it only the access needed and keep review points for important changes. When something goes wrong, disconnect unsafe access, preserve useful evidence, and follow the actual provider’s recovery process. A preparation checklist helps you respond calmly.'),
'A person receives a voice message that sounds like a coworker asking for an urgent payment. Instead of relying on the voice, they contact the coworker through the known company channel and confirm the request is false. Later they review payment approval rules and account protections. The useful habit is verifying the authority and request through an independent route, not trying to identify every synthetic voice by ear.',
'Create an account-protection checklist for three important accounts. Verify recovery options, MFA, updates, and backups. Write a response plan for one suspicious request and practice with fictional information.',
[('Which password practice helps?',['One password everywhere','Unique passwords managed securely','Sharing passwords in chat'],1,'A compromised password should not expose every account.'),('How should you verify an urgent payment message?',['Use only its supplied link','Contact the person through a known channel','Trust the familiar voice'],1,'Independent verification checks the authority of the request.'),('What should you do before uploading work records to AI?',['Check permission and data practices','Assume every tool is private','Include extra private details'],0,'Data handling and organizational permission matter.')]]}
assert len(units)==20
references={
'leadership':[('Center for Creative Leadership. (2026). What is leadership?','https://www.ccl.org/articles/leading-effectively-articles/what-is-leadership-a-definition/')],
'amazon-business':[('Amazon. (n.d.). KDP content guidelines.','https://kdp.amazon.com/help/topic/G200672390'),('ACX. (n.d.). Audio submission requirements.','https://help.acx.com/s/article/what-are-the-acx-audio-submission-requirements'),('Amazon. (n.d.). Merch on Demand FAQs.','https://merch.amazon.com/resource/201846470'),('Amazon. (n.d.). Selling plans and pricing.','https://sell.amazon.com/pricing'),('Amazon. (n.d.). Associates program.','https://affiliate-program.amazon.com/help/operating/agreement/')],
'music-ai':[('U.S. Copyright Office. (n.d.). Copyright and artificial intelligence.','https://www.copyright.gov/ai/')],
'digital-safety':[('National Institute of Standards and Technology. (n.d.). AI Risk Management Framework.','https://www.nist.gov/itl/ai-risk-management-framework'),('Cybersecurity and Infrastructure Security Agency. (n.d.). Secure Our World.','https://www.cisa.gov/secure-our-world')],
'web-design':[('MDN contributors. (n.d.). Learn web development.','https://developer.mozilla.org/en-US/docs/Learn_web_development')],
'learning-products':[('Carnegie Mellon University. (n.d.). Aligning assessment with objectives.','https://www.cmu.edu/teaching/assessment/basics/alignment.html')],
'purpose-momentum':[('University of North Carolina Learning Center. (n.d.). SMART goals.','https://learningcenter.unc.edu/tips-and-tools/setting-goals/')],
'career-ai':[('CareerOneStop. (n.d.). Explore careers.','https://www.careeronestop.org/ExploreCareers/explore-careers.aspx')],
'digital-marketing':[('Federal Trade Commission. (n.d.). Advertising and marketing.','https://www.ftc.gov/business-guidance/advertising-marketing')],
'customer-experience':[('Federal Trade Commission. (n.d.). Advertising and marketing.','https://www.ftc.gov/business-guidance/advertising-marketing')]}
def sources(key):
 return references.get(key,[('U.S. Small Business Administration. (n.d.). Manage your business.','https://www.sba.gov/counseling/manage-your-business/'),('National Institute of Standards and Technology. (n.d.). AI Risk Management Framework.','https://www.nist.gov/itl/ai-risk-management-framework')])
def foundation_markup(key):
 u=units[key];questions=u[5];parts=[]
 for i,(heading,body) in enumerate(u[:3]):
  q,opts,answer,why=questions[i]
  parts.append(f'<section class="unit-step"><span class="eyebrow">Learn & apply · {i+1}</span><h3>{E(heading)}</h3><p>{E(body)}</p><fieldset class="unit-check" data-unit-question="{i}"><legend>Check your understanding</legend><p>{E(q)}</p>'+''.join(f'<button type="button" data-choice="{j}" aria-pressed="false">{E(t)}</button>' for j,t in enumerate(opts))+'<p class="unit-feedback" role="status"></p></fieldset></section>')
 data=[{'answer':q[2],'why':q[3]} for q in questions]
 return '<section id="foundation-unit" class="foundation-unit"><span class="eyebrow">Published foundation lesson</span><h2>Learn it. Try it. Make it yours.</h2><p class="unit-note">This introductory lesson is ready to use. The six-module curriculum below shows the larger course being developed. Take any course independently.</p>'+''.join(parts)+f'<section class="unit-example"><span class="eyebrow">Worked example · Illustrative scenario</span><h3>See the idea in action.</h3><p>{E(u[3])}</p></section><section class="unit-project"><span class="eyebrow">Apply & create</span><h3>Build a small result.</h3><p>{E(u[4])}</p><details><summary>Review your work against these criteria →</summary><ul><li>Clarity: Can another person understand your goal and steps?</li><li>Evidence: Are your important claims checked against the source?</li><li>Usefulness: Does your result work in the actual situation?</li><li>Transfer: What would you change for a different person or constraint?</li></ul><p>Ask someone to try your result when practical. Use their experience to revise one choice. The three questions check understanding; the project checks what you can actually do.</p></details><label for="unit-notes">Your decisions and application notes</label><textarea id="unit-notes" data-plan="unit-notes" placeholder="Describe your result, evidence, and next revision."></textarea><p class="small">Notes stay in this browser when storage is available. Include them in your downloaded learning plan below.</p><div class="reader-actions"><button type="button" class="platinum" id="check-unit">Review my answers →</button></div><p id="unit-result" role="status"></p></section><section class="unit-sources"><h3>Reference shelf.</h3><p>Original InAct explanation and illustrative examples. These primary sources support further study; platform terms should be checked again before use. References use an APA-style organization, date, and title. Sources without a verified publication date are marked n.d.</p><ul>'+''.join(f'<li><a href="{url}" target="_blank" rel="noopener noreferrer">{E(label)} ↗</a></li>' for label,url in sources(key))+'</ul></section></section><script type="application/json" id="course-unit-data">'+json.dumps(data).replace('<','\\u003c')+'</script>'
