import html
E=html.escape
contexts={
'purpose-momentum':('purpose, habit, and feedback','a seven-day practice routine','A learner wants to study for two hours each night but keeps missing the plan. They have ten quiet minutes after breakfast.','Choose one ten-minute task tied to a useful goal. Keep a short record for seven days. Compare the plan with what actually happened before making it larger.'),
'ai-foundations':('app, model, prompt, and source','a checked AI-assisted draft','An AI tool drafts a meeting agenda and invents a deadline that nobody agreed to.','Treat the draft as material to review. Check every date against the actual request, remove unsupported details, and record what a person must approve.'),
'everyday-ai':('a task, a priority, and a life flow','a weekly planning flow','A calendar draft puts two appointments at the same time and leaves no travel time.','Compare the draft with the actual appointments. Add travel and recovery time, then choose a plan that fits the person’s priorities rather than accepting the fastest-looking schedule.'),
'small-business':('customer, offer, revenue, and cash flow','a small customer test','A founder buys a logo before checking whether anyone needs the service.','Name a customer group and a specific problem. Talk to potential customers and test a simple offer before spending heavily on branding or software.'),
'business-funding':('a loan, a credit line, a grant, and equity','a funding-readiness checklist','A business needs equipment but has not calculated how the purchase would affect monthly cash flow.','Identify the amount, purpose, expected benefit, and repayment capacity using verified figures. Compare actual terms and eligibility before selecting a funding source. Do not assume a grant or approval is available.'),
'business-workflows':('input, process, reviewer, and output','a workflow with a review step','An AI workflow drafts customer replies but sends them before anyone checks the customer record.','Separate preparation from authority to send. Map the steps, require the responsible person’s review, and test a missing-information case before turning on automation.'),
'digital-marketing':('audience, message, channel, and useful result','a measurable content test','A shop celebrates many post views but receives no inquiries about its service.','Check whether the content answers the intended customer’s question. Make the next action clear and measure inquiries as well as views. Change one part of the message at a time.'),
'web-design':('HTML structure, visual style, and interaction','a small accessible page','A contact button looks attractive but cannot be reached with the keyboard.','Test the page with a keyboard and on a phone. Use a proper link or button, make its purpose clear, and verify that the destination works before treating the design as ready.'),
'music-ai':('a song, a recording, a producer, and distribution','a creative brief and release checklist','A music creator has many generated drafts but cannot explain which one fits the project.','Write the listening goal before comparing drafts. Identify audible reasons for the choice and check the materials, permissions, credits, and distributor requirements before release.'),
'learning-products':('a learning outcome, an example, practice, and feedback','a small learning product','A lesson presents a long explanation and asks only whether the learner liked it.','Choose a skill the learner should demonstrate. Show a worked example, let them practice, and give useful feedback. Check whether they can apply the idea to a new case.'),
'ai-music-production':('a creative brief, a stem, and an arrangement','a production comparison with audible evidence','A creator keeps generating new tracks without naming the intended listening experience.','Use one clear brief and compare a few drafts against it. Record the audible decisions behind your selection and the checks still needed before release.'),
'ai-search-marketing':('a customer question, supporting evidence, and a next action','an answer-first content plan','A service page promises to be the best but never answers a customer’s actual question.','Name the customer’s decision, provide relevant evidence, and offer one useful next step. Evaluate clarity and resulting actions rather than promising a search ranking.'),
'business-agents':('an input, a review gate, and an authorized action','a workflow pilot with a boundary test','An agent can draft a reply, but the company has not decided who may authorize sending it.','Write the decision boundary and identify the responsible reviewer. Test a routine case and a case with missing information before giving the workflow wider access.'),
'realtime-music':('musical intent, a control, and an audible response','a small interactive listening test','A music app has many controls, but a new listener cannot tell which change affects the sound.','Test one control at a time. Ask the listener to describe what changed and whether it helped their musical goal. Use that evidence to improve the control labels.'),
'ai-artist-identities':('a project, a fictional persona, and the responsible people','a clear experimental-artist introduction','A listener mistakes a fictional artist portrait for a real singer with an invented career.','Make the project’s identity clear where listeners first encounter it. Describe the human direction accurately and test whether a new reader understands the relationship.')}
def learning_markup(key):
 terms,task,case,feedback=contexts[key]
 goals=[f'Explain {terms} in your own words.',f'Apply the idea by preparing {task}.',f'Compare choices, check the evidence, and revise your work after feedback.']
 diagram='<svg class="learning-map" viewBox="0 0 680 100" role="img" aria-label="Explain, apply, check, and build a useful result"><path d="M70 35H610" stroke="currentColor" opacity=".25"/><path class="learning-pulse" d="M70 35H610" stroke="currentColor" fill="none" stroke-width="3"/>'+''.join(f'<circle cx="{70+i*180}" cy="35" r="10" fill="currentColor"/><text x="{70+i*180}" y="78" text-anchor="middle" fill="currentColor" font-family="Georgia" font-size="18">{t}</text>' for i,t in enumerate(['Explain','Apply','Check','Build']))+'</svg>'
 return '<section class="learning-goals"><span class="eyebrow">A useful result</span><h2>What you’ll be able to do.</h2><ul>'+''.join('<li>'+E(g)+'</li>' for g in goals)+'</ul>'+diagram+'</section><section class="practice-case"><span class="eyebrow">Try a decision · Illustrative example</span><h2>What would you change first?</h2><p>'+E(case)+'</p><p>Pause and choose your first action. Explain why it would help before opening the example response.</p><details><summary>Compare your reasoning →</summary><p>'+E(feedback)+'</p></details></section>'
