const PUBLISHED_TRACKS=__MUSIC_TRACKS__;
const genres=['Afrobeats','Ambient','Blues','Classical','Country','EDM','Experimental','Funk','Gospel','Hip-Hop','House / Club','Jazz','Latin','Lo-Fi','Pop','R&B','Reggae','Rock','Soul','Soundtracks','Sound Effects'];
for(const id of ['listen-genre','upload-genre']){$('#'+id).innerHTML=(id==='listen-genre'?'<option value="All genres">All genres</option>':'')+genres.map(g=>`<option>${g}</option>`).join('')}
$('#upload-genre').value='Soul';let tracks=[...PUBLISHED_TRACKS],currentTrack=null,shuffle=false,repeat=false;const audio=$('#audio');audio.hidden=true;
function setMusicOpen(open){if(open&&innerWidth<1100&&!$('#release-panel').hidden)setReleaseOpen(false);$('#music-panel').hidden=!open;$('#music-toggle').setAttribute('aria-expanded',String(open));$('#music-toggle').setAttribute('aria-label',open?'Close music player':'Open music player');if(open)$('#listen-genre').focus()}
$('#music-toggle').onclick=()=>setMusicOpen($('#music-panel').hidden);$('#music-close').onclick=()=>{setMusicOpen(false);$('#music-toggle').focus()};document.addEventListener('click',e=>{if(!e.composedPath().some(el=>el.classList?.contains('music-wrap')||el.classList?.contains('official-soul-panel')||el.id==='release-panel'))setMusicOpen(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#release-panel').hidden){setReleaseOpen(false);$('#open-release').focus()}else if(!$('#music-panel').hidden){setMusicOpen(false);$('#music-toggle').focus()}else if(officialSoulPanel)closeOfficialSoul()}});
function setReleaseOpen(open){$('#release-panel').hidden=!open;$('#open-release').setAttribute('aria-expanded',String(open));if(open){audio.pause();if(ytPlayer?.pauseVideo)ytPlayer.pauseVideo();if(innerWidth<1100)setMusicOpen(false);$('#release-close').focus()}}
$('#open-release').onclick=()=>setReleaseOpen($('#release-panel').hidden);$('#release-close').onclick=()=>{setReleaseOpen(false);$('#music-toggle').focus()};
let officialSoulPanel=null,ytPlayer=null,ytReady=false,videoEpoch=0,apiPromise=null;
function paintPlay(playing){$('#music-toggle').classList.toggle('playing',playing);$('#master-play').textContent=playing?'Pause Ⅱ':'Play ▶';$('#master-play').setAttribute('aria-label',playing?'Pause current track':'Play current track')}
function closeOfficialSoul(){videoEpoch++;try{ytPlayer?.destroy()}catch{}ytPlayer=null;ytReady=false;officialSoulPanel?.remove();officialSoulPanel=null;paintPlay(false);$('#master-play').disabled=false;}
function youtubeAPI(){if(window.YT?.Player)return Promise.resolve(window.YT);if(apiPromise)return apiPromise;apiPromise=new Promise((resolve,reject)=>{const prior=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{if(prior)prior();resolve(window.YT)};const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';s.onerror=()=>{apiPromise=null;reject(Error('Player controls could not load'))};document.head.append(s)});return apiPromise}
function openOfficialSoul(){const t=PUBLISHED_TRACKS.find(t=>t.genre==='Soul');playTrack(t)}
async function openMusicVideo(t,version=0){closeOfficialSoul();const epoch=videoEpoch,ids=[t.videoId,...(t.alternates||[])];audio.pause();audio.hidden=true;ytReady=false;$('#master-play').disabled=true;officialSoulPanel=document.createElement('aside');officialSoulPanel.className='official-soul-panel';officialSoulPanel.setAttribute('aria-label',t.artist+' music video player');officialSoulPanel.innerHTML=`<div class="official-soul-heading"><span>${esc(t.artist)} · ${esc(t.title)}</span><button type="button" aria-label="Close music video">×</button></div><iframe id="ie-youtube-player" title="${esc(t.artist)}: ${esc(t.title)}" src="https://www.youtube-nocookie.com/embed/${ids[version]}?autoplay=1&playsinline=1&enablejsapi=1&rel=0&origin=${encodeURIComponent(location.origin)}" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe><p class="video-player-note" role="status">Publisher player · Press play in the video if needed.</p><p><a href="https://www.youtube.com/watch?v=${ids[version]}" target="_blank" rel="noopener noreferrer">Open on YouTube ↗</a></p>`;document.body.append(officialSoulPanel);officialSoulPanel.querySelector('button').onclick=closeOfficialSoul;const note=()=>officialSoulPanel?.querySelector('.video-player-note');setTimeout(()=>{if(epoch===videoEpoch&&!ytReady&&note())note().textContent='Use the video’s own playback controls. Shared controls are still connecting.'},6000);
 try{const YT=await youtubeAPI();if(epoch!==videoEpoch||!officialSoulPanel)return;ytPlayer=new YT.Player('ie-youtube-player',{events:{onReady:e=>{if(epoch!==videoEpoch)return;ytReady=true;$('#master-play').disabled=false;e.target.setVolume(Number($('#music-volume').value));e.target.playVideo()},onStateChange:e=>{if(epoch!==videoEpoch)return;paintPlay(e.data===1);if(e.data===0){if(repeat){e.target.seekTo(0);e.target.playVideo()}else if(visibleTracks().length>1)stepTrack(1)}},onAutoplayBlocked:()=>{if(note())note().textContent='Press Play in the video or music controller to begin.'},onError:e=>{if(epoch!==videoEpoch)return;paintPlay(false);$('#master-play').disabled=false;if([100,101,150].includes(e.data)&&version+1<ids.length){$('#now-playing').textContent='Trying an alternate publisher version…';openMusicVideo(t,version+1)}else{if(note())note().textContent='This publisher video is unavailable here. Try the next track or open its YouTube link.'}}}})}catch{if(epoch===videoEpoch&&note())note().textContent='Use the video’s own controls. Shared playback controls are unavailable.'}}
function visibleTracks(){return tracks.filter(t=>$('#listen-genre').value==='All genres'||t.genre===$('#listen-genre').value)}
function renderPlaylist(){renderGenreChips();const list=visibleTracks();$('#playlist').replaceChildren();if(!list.length){const li=document.createElement('li');li.className='small';li.textContent='Our ie sound effects collection is being prepared. Original effects will appear here with previews and purchase links when published.';$('#playlist').append(li)}list.forEach(t=>{const li=document.createElement('li'),b=document.createElement('button');b.innerHTML=`${esc(t.artist||'Local audio')} · ${esc(t.title)}<small>${esc(t.genre)} · ${t.videoId?'Publisher video':'Local audio'}</small>`;b.setAttribute('aria-current',String(currentTrack===t));b.onclick=()=>playTrack(t);li.append(b);if(t.inact){const mark=document.createElement('small');mark.textContent='InAct Entertainment Music';li.append(mark);const actions=document.createElement('div');actions.className='track-product-actions';const video=document.createElement('button');video.className='platinum';video.type='button';video.textContent=t.videoId?'Play video →':'Video coming soon';video.disabled=!t.videoId;video.onclick=()=>playTrack(t);actions.append(video);if(t.buyUrl){const buy=document.createElement('a');buy.className='platinum';buy.href=t.buyUrl;buy.target='_blank';buy.rel='noopener noreferrer';buy.textContent=t.genre==='Sound Effects'?'Buy this sound effect ↗':'Buy this music ↗';actions.append(buy)}li.append(actions)}$('#playlist').append(li)});$('#prev').disabled=$('#next').disabled=list.length<2;$('#shuffle').disabled=list.length<2}
async function playTrack(t){if(!t)return;if(!t.videoId&&!t.src){toast('This preview is being prepared.');return;}currentTrack=t;if(!$('#release-panel').hidden)setReleaseOpen(false);$('#now-playing').textContent=`${t.artist||'Local audio'} · ${t.title} · ${t.genre}`;$('#music-track-theme').textContent=t.theme||'Your local audio stays in this browser session.';renderPlaylist();if(t.videoId){openMusicVideo(t);return}closeOfficialSoul();audio.hidden=false;audio.src=t.src;audio.volume=Number($('#music-volume').value)/100;try{await audio.play()}catch{toast('Use the audio controls to begin listening.')}}
function stepTrack(direction){const list=visibleTracks();if(!list.length)return;const index=list.indexOf(currentTrack);let nextIndex=index<0?0:(index+direction+list.length)%list.length;if(shuffle&&list.length>1){const other=list.filter(t=>t!==currentTrack);playTrack(other[Math.floor(Math.random()*other.length)]);return}playTrack(list[nextIndex])}
function chooseGenre(g){$('#listen-genre').value=g;renderPlaylist();const list=visibleTracks(),first=list.find(t=>t.local)||list[0];$('#master-play').disabled=!first;if(first)playTrack(first);else{audio.pause();closeOfficialSoul();currentTrack=null;$('#now-playing').textContent='Sound Effects · Original previews coming soon';paintPlay(false)}}
function renderGenreChips(){if(!$('#genre-chips'))return;$('#genre-chips').replaceChildren();genres.forEach(g=>{const b=document.createElement('button');b.type='button';const t=tracks.find(t=>t.genre===g&&t.local)||tracks.find(t=>t.genre===g),preview=t?(t.artist||'Local audio')+' · '+t.title:'More tracks coming soon';b.innerHTML=esc(g)+`<span class="genre-tooltip">${esc(preview)}</span>`;b.title=preview;b.setAttribute('aria-label',g+': '+preview);b.setAttribute('aria-pressed',String($('#listen-genre').value===g));b.onmouseenter=b.onfocus=()=>$('#genre-preview').textContent=g+': '+preview;b.onclick=()=>chooseGenre(g);$('#genre-chips').append(b)})}
$('#listen-genre').onchange=()=>chooseGenre($('#listen-genre').value);$('#prev').onclick=()=>stepTrack(-1);$('#next').onclick=()=>stepTrack(1);$('#shuffle').onclick=()=>{shuffle=!shuffle;$('#shuffle').setAttribute('aria-pressed',String(shuffle))};$('#repeat').onclick=()=>{repeat=!repeat;audio.loop=repeat;$('#repeat').setAttribute('aria-pressed',String(repeat))};$('#master-play').onclick=()=>{if(!currentTrack){playTrack(visibleTracks()[0]);return}if(currentTrack.videoId){if(!officialSoulPanel){openMusicVideo(currentTrack);return}if(!ytReady){toast('Use Play in the video while shared controls connect.');return}if(ytPlayer.getPlayerState()===1)ytPlayer.pauseVideo();else ytPlayer.playVideo()}else if(audio.paused)audio.play().catch(()=>toast('Use the audio controls.'));else audio.pause()};$('#music-volume').oninput=()=>{audio.volume=Number($('#music-volume').value)/100;if(ytReady)ytPlayer.setVolume(Number($('#music-volume').value))};audio.onplay=()=>paintPlay(true);audio.onpause=()=>{if(!ytReady)paintPlay(false)};audio.onended=()=>{if(!repeat&&visibleTracks().length>1)stepTrack(1)};audio.onerror=()=>toast('This local audio could not be played. Try another supported format.');
$('#music-files').onchange=e=>{const incoming=[...e.target.files].filter(f=>f.type.startsWith('audio/')||/\.(mp3|wav|m4a|ogg|flac)$/i.test(f.name));for(const f of incoming)tracks.push({title:f.name.replace(/\.[^.]+$/,''),artist:'Local audio',genre:$('#upload-genre').value,src:URL.createObjectURL(f),local:true});$('#listen-genre').value=$('#upload-genre').value;renderPlaylist();if(incoming.length)playTrack(visibleTracks().at(-1));toast(`${incoming.length} local track${incoming.length===1?'':'s'} added`);e.target.value=''};$('#clear-tracks').onclick=()=>{closeOfficialSoul();audio.pause();audio.removeAttribute('src');audio.load();audio.hidden=true;for(const t of tracks)if(t.local)URL.revokeObjectURL(t.src);tracks=[...PUBLISHED_TRACKS];currentTrack=null;$('#now-playing').textContent='Choose a genre. Familiar classics await.';$('#music-track-theme').textContent='';renderPlaylist()};renderPlaylist();
